name: "Ruby on Rails CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Trigger Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          curl -s https://api.render.com/deploy/srv-csu1sjlumphs738kicig?key=kT4m5lDQnHA
